name: hamiltonicity
version: 0.1.0.0
github: "githubuser/hamiltonicity"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2018 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/hamiltonicity#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - matrix
    - safe
    - vector
    - containers
    - random-fu

tests:
  tests:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - hamiltonicity
      - hedgehog
      - tasty
      - tasty-hedgehog
      - containers

executables:
  hamiltonicity-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hamiltonicity
