name: hamiltonicity
version: 0.1.0.0
github: frontsideair/hamiltonicity
license: BSD3
author: Fatih Altinok
maintainer: fatihaltinok@live.com
copyright: 2018 Fatih Altinok
description: >-
  Please see the README on GitHub at
  <https://github.com/frontsideair/hamiltonicity#readme>
dependencies:
  - base >= 4.7 && < 5
  - safe
library:
  source-dirs: src
  dependencies:
    - matrix
    - safe
    - vector
    - containers
    - random-fu
tests:
  tests:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - hamiltonicity
      - hedgehog
      - tasty
      - tasty-hedgehog
      - containers
executables:
  hamiltonicity:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - "-threaded"
      - "-rtsopts"
      - "-with-rtsopts=-N"
    dependencies:
      - hamiltonicity
      - optparse-applicative
